### ISSUE TITLE
Apply wireframe with minimum content

### ISSUE THREAD

**Issue by iniquitousriddle** [iniquitousriddle/iniquitousriddle.github.io#1]
@jamowelling 
Mock up a skeleton. Apply changes to CSS and HTML files. Design choice entirely up to you. As for content, this landing page might include links to each of our github accounts. Content is also open to your vision for the page. Remember small commits. One improvement at a time.

**Comment by jamowelling** [comment]
@noahschutte basic page design is up and running. I've got ideas for how to improve it down the road, but some of that is above my head at the moment.
